groups:

  - name: interndata_a1
    match: "A1|a1"
    total_weight: 0.2
    inside: frames_pow
    gamma: 1.0

  - name: agibotworld
    match: "agibotworld"
    total_weight: 0.25
    inside: frames_pow 
    gamma: 1.0

  - name: galaxea
    match: "galaxea"
    total_weight: 0.2
    inside: frames_pow 
    gamma: 1.0

  - name: robomind
    match: "robomind"
    total_weight: 0.1
    inside: frames_pow 
    gamma: 1.0

  - name: droid
    match: "droid"
    total_weight: 0.15
    inside: frames_pow
    gamma: 1.0
  
  - name: fastumi
    match: "fastumi"
    total_weight: 0.1
    inside: frames_pow 
    gamma: 1.0

default:
  total_weight: 0.1
  inside: frames_pow
  gamma: 1.0
