# Franka with Robotiq gripper (A1 old format)
robot_type: frankarobotiq
action_mask_spec: [7, -1]
feature_mapping:
  observation.state:
    - states.joint.position
    - states.gripper.position
  action:
    - actions.joint.position
    - actions.gripper.position
image_mapping:
  images.rgb.head: observation.images.image0
  images.rgb.hand: observation.images.image1
description: "Franka with Robotiq gripper (A1 old format)"