robot_type: calvin_franka
action_mask_spec: [6, -1]
action_reorder:
  - [0, 6, 0, 6]
  - [6, 7, 7, 8]
state_reorder:
  - [0, 6, 0, 6]
  - [6, 7, 7, 8]
feature_mapping:
  observation.state:
    - state.ee_pos
    - state.ee_rot
    - state.gripper
  action:
    - action.delta_ee_pos
    - action.delta_ee_rot
    - action.gripper
image_mapping:
  video.image_base: observation.images.image0
  video.image_wrist: observation.images.image1
action_mode: end_effector
description: "CALVIN benchmark Franka robot (end-effector pose + gripper)"
