# fast umi single
robot_type: fastumi-single
action_mask_spec: [3,-5]
feature_mapping:
  observation.state:
    - observation.state
  action:
    - action
image_mapping:
  observation.images.front: observation.images.image0
action_mode: end_effector
description: "fast umi single"