# fast umi single
robot_type: fastumi-dual
action_mask_spec: [3,-5,3,-5]
feature_mapping:
  observation.state:
    - observation.state
  action:
    - action
image_mapping:
  observation.images.robot_0_image: observation.images.image0
  observation.images.robot_1_image: observation.images.image1
action_mode: end_effector
description: "fast umi dual"