robot_type: "franka_droid"
# action_mask_spec: [7, -1]
action_mask_spec: [6, -1]
feature_mapping:
  observation.state:
    # - observation.state.joint_position
    - observation.state.cartesian_position
    - observation.state.gripper_position
  action:
    # - action.joint_position
    - action.cartesian_position
    - action.gripper_position
image_mapping:
  observation.images.exterior_1_left: observation.images.image0
  observation.images.exterior_2_left: observation.images.image1
  observation.images.wrist_left: observation.images.image2
action_mode: end_effector
description: "Franka Emika Panda robot (droid)"