# UR5 RobotWin robot
robot_type: ur5_robotwin
action_mask_spec: [6, -1]
action_reorder:
  - [0, 6, 0, 6]
  - [6, 7, 7, 8]
state_reorder:
  - [0, 6, 0, 6]
  - [6, 7, 7, 8]
feature_mapping:
  observation.state:
    - observation.state
  action:
    - action
image_mapping:
  observation.images.cam_high: observation.images.image0
  observation.images.cam_left_wrist: observation.images.image1
  observation.images.cam_right_wrist: observation.images.image2
description: "UR5 RobotWin robot"