# AgileX ALOHA RobotWin dual-arm robot (uses end-effector pose)
robot_type: aloha_robotwin
# action_mask_spec: [6, 3, -4, -1, 6, 3, -4, -1]
action_mask_spec: [3, -4, -1, 3, -4, -1]
feature_mapping:
  observation.state:
    # - state.left.joint_angles
    - state.left.eep.position
    - state.left.eep.orientation
    - state.left.gripper
    # - state.right.joint_angles
    - state.right.eep.position
    - state.right.eep.orientation
    - state.right.gripper
  action:
    # - action.left.joint_angles
    - action.left.eep.position
    - action.left.eep.orientation
    - action.left.gripper
    # - action.right.joint_angles
    - action.right.eep.position
    - action.right.eep.orientation
    - action.right.gripper
image_mapping:
  observation.images.cam_high: observation.images.image0
  observation.images.cam_left_wrist: observation.images.image1
  observation.images.cam_right_wrist: observation.images.image2
action_mode: end_effector
description: "AgileX ALOHA RobotWin dual-arm robot (end-effector pose)"