robot_type: robocasa_piper
action_mask_spec: [6, -6]
feature_mapping:
  observation.state:
    - states.gripper.pos
    - states.gripper.quat
    - states.joint.position
    - states.gripper.position
  action:
    - actions.joint.position
image_mapping:
  robot0_agentview_left_image: observation.images.image0
  robot0_agentview_right_image: observation.images.image1
  robot0_eye_in_hand_image: observation.images.image2
description: "RoboCasa benchmark Piper robot (joint position + 3 cameras)"
